import { FormEvent, useState } from 'react'
import { CheckCircle2, Eye, Save, ShieldCheck } from 'lucide-react'
import { useAuth } from '../../lib/auth'

export function ProfilePage() {
  const { profile } = useAuth()
  const [saved, setSaved] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); setSaved(true); window.setTimeout(() => setSaved(false), 3000) }
  return <div><header className="page-header"><div><p className="eyebrow">Your information</p><h1>My profile</h1><p>Choose what other approved family members can see and how they can reach you.</p></div></header><form className="profile-form" onSubmit={submit}><section className="panel"><div className="section-title"><div><h2>Profile details</h2><p>Basic information used in the family directory.</p></div><span className="avatar avatar--xl">{profile?.first_name[0]}{profile?.last_name[0]}</span></div><div className="field-grid"><label>First name<input defaultValue={profile?.first_name} /></label><label>Middle name<input /></label><label>Last name<input defaultValue={profile?.last_name} /></label><label>Preferred name<input defaultValue={profile?.first_name} /></label><label>Email address<input type="email" defaultValue={profile?.email} /></label><label>Phone<input type="tel" placeholder="(555) 000-0000" /></label></div></section><section className="panel"><div className="section-title"><div><h2>Birthday & household</h2><p>Birthday year and address visibility can be limited.</p></div><Eye /></div><div className="field-grid"><label>Birthdate<input type="date" /></label><label>Birthday visibility<select defaultValue="month_day"><option value="full">Full birthdate</option><option value="month_day">Month and day only</option><option value="private">Keep private</option></select></label><label>Household<select><option>Not assigned</option><option>Northside household</option></select></label><label>Family branch<input placeholder="For example: Wisconsin branch" /></label></div></section><section className="panel"><div className="section-title"><div><h2>Location & family notes</h2><p>Share only what helps the family stay connected.</p></div><ShieldCheck /></div><label>Street address<input autoComplete="street-address" /></label><div className="field-grid field-grid--three"><label>City<input autoComplete="address-level2" /></label><label>State<input autoComplete="address-level1" /></label><label>Postal code<input autoComplete="postal-code" /></label></div><label>Relationship notes<textarea rows={4} placeholder="Share how you connect to the family or details you would like preserved." /></label></section><div className="form-save-bar"><p>{saved && <span role="status"><CheckCircle2 /> Changes saved in preview mode</span>}</p><button className="button"><Save /> Save profile</button></div></form></div>
}
