import { useState } from 'react'
import { Check, Clock3, Mail, MessageSquareText, MoreHorizontal, Phone, UserRoundCheck, X } from 'lucide-react'
import { accessRequests as mockRequests } from '../../data/mock'
import type { AccessRequest } from '../../types'

export function ApprovalsPage() {
  const [requests, setRequests] = useState<AccessRequest[]>(mockRequests)
  const [notice, setNotice] = useState('')
  const update = (id: string, status: AccessRequest['status']) => { setRequests(current => current.map(item => item.id === id ? { ...item, status } : item)); setNotice(status === 'approved' ? 'Request approved in preview mode.' : 'Request status updated in preview mode.') }
  return <div><header className="page-header"><div><p className="eyebrow eyebrow--admin">Administration</p><h1>Access approvals</h1><p>Review identity and family connection before granting access. Approval is always manual.</p></div><span className="count-badge">{requests.filter(item => item.status === 'pending').length} pending</span></header>{notice && <div className="inline-success" role="status"><Check />{notice}<button onClick={() => setNotice('')} aria-label="Dismiss"><X /></button></div>}<div className="approval-list">{requests.map(request => <article className={`approval-card ${request.status !== 'pending' ? 'is-reviewed' : ''}`} key={request.id}><div className="approval-person"><span className="avatar avatar--large">{request.first_name[0]}{request.last_name[0]}</span><div><div className="approval-title"><h2>{request.first_name} {request.last_name}</h2><span className={`status-badge status-${request.status}`}>{request.status.replace('_', ' ')}</span></div><p>Requested {new Date(request.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}</p></div><button className="icon-button" aria-label="More actions"><MoreHorizontal /></button></div><div className="approval-details"><div><Mail /><span><small>Email</small><a href={`mailto:${request.email}`}>{request.email}</a></span></div>{request.phone && <div><Phone /><span><small>Phone</small><strong>{request.phone}</strong></span></div>}<div><UserRoundCheck /><span><small>Relationship</small><strong>{request.relationship}</strong></span></div><div><UserRoundCheck /><span><small>Verifier</small><strong>{request.verifier}</strong></span></div>{request.message && <div className="approval-message"><MessageSquareText /><span><small>Message</small><p>{request.message}</p></span></div>}</div>{request.status === 'pending' && <div className="approval-actions"><button className="button button--approve" onClick={() => update(request.id, 'approved')}><Check /> Approve</button><button className="button button--secondary" onClick={() => update(request.id, 'more_info')}><MessageSquareText /> Ask for info</button><button className="button button--danger" onClick={() => update(request.id, 'denied')}><X /> Deny</button></div>}</article>)}</div><div className="admin-footnote"><Clock3 /><p><strong>Backend integration pending.</strong> Actions currently update local preview state only. The production handler must update Supabase, write an audit entry, and send the appropriate Resend template.</p></div></div>
}
